<x-layouts.app title="Dashboard">
    <div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">Operations overview</p><h1 class="page-title">Good {{ now()->hour < 12 ? 'morning' : (now()->hour < 18 ? 'afternoon' : 'evening') }}, {{ Str::before(auth()->user()->name, ' ') }}</h1><p class="page-copy">Confirmed device state, value, and connectivity at a glance.</p></div><a class="primary-button" href="{{ route('devices.create') }}">+ Register device</a></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Devices',$stats['devices'],'indigo'],['Portfolio value',number_format($stats['value'],2).' LKR','blue'],['Locked',$stats['locked'],'red'],['Unlocked',$stats['unlocked'],'emerald'],['Offline',$stats['offline'],'slate'],['Released',$stats['released'],'cyan']] as [$label,$value,$tone])
            <article class="metric-card"><div class="mb-5 flex items-center justify-between"><p class="text-sm font-semibold text-slate-500">{{ $label }}</p><span class="size-2.5 rounded-full bg-{{ $tone }}-500"></span></div><p class="text-2xl font-black tracking-tight text-slate-950">{{ $value }}</p></article>
        @endforeach
        @if($stats['admins'] !== null)<article class="metric-card"><p class="mb-5 text-sm font-semibold text-slate-500">Shop Owners</p><p class="text-2xl font-black">{{ $stats['admins'] }}</p></article>@endif
    </div>
    <div class="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">@foreach([['Offline protected',$stats['offline_protected']],['Deadline within 24h',$stats['deadline_24h']],['Offline over 24h',$stats['offline_24h']],['Offline locked',$stats['offline_locked']],['Policy pending',$stats['policy_pending']]] as [$label,$value])<article class="metric-card"><p class="text-sm font-semibold text-slate-500">{{ $label }}</p><p class="mt-3 text-2xl font-black">{{ $value }}</p></article>@endforeach</div>
    <div class="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Customers',$stats['customers']],['Active managed devices',$stats['active_devices']],['Customer payments','LKR '.number_format($stats['customer_paid'],2)],['Payments received today','LKR '.number_format($stats['payments_today'],2)],['Customer outstanding','LKR '.number_format($stats['customer_outstanding'],2)],['Overdue installments','LKR '.number_format($stats['overdue_installments'],2)],['Platform commission','LKR '.number_format($stats['commission_total'],2)],['Commission paid','LKR '.number_format($stats['commission_paid'],2)],['Commission outstanding','LKR '.number_format($stats['commission_outstanding'],2)],['New devices today',$stats['new_devices_today']],['SMS sent today',$stats['sms_sent_today']],['SMS failed today',$stats['sms_failed_today']]] as [$label,$value])<article class="metric-card"><p class="text-sm font-semibold text-slate-500">{{ $label }}</p><p class="mt-3 text-2xl font-black">{{ $value }}</p></article>@endforeach @if($stats['shops']!==null)<article class="metric-card"><p class="text-sm font-semibold text-slate-500">Active shops</p><p class="mt-3 text-2xl font-black">{{ $stats['active_shops'] }} / {{ $stats['shops'] }}</p></article><article class="metric-card"><p class="text-sm font-semibold text-slate-500">Inactive shops</p><p class="mt-3 text-2xl font-black">{{ $stats['inactive_shops'] }}</p></article>@endif</div>
    <section class="panel mt-7"><div class="panel-header"><div><h2 class="section-title">Recent devices</h2><p class="section-copy">State changes are shown only after confirmation from the Android app.</p></div><a class="text-sm font-semibold text-indigo-600" href="{{ route('devices.index') }}">View all →</a></div>
        <div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Customer</th><th>Device</th><th>Value</th><th>Mode</th><th>Status</th><th>Last online</th></tr></thead><tbody>
        @forelse($devices as $device)<tr class="cursor-pointer" onclick="location.href='{{ route('devices.show',$device) }}'"><td><p class="font-semibold">{{ $device->customer->name }}</p><p class="text-xs text-slate-500">{{ $device->customer->phone }}</p></td><td>{{ $device->brand }} {{ $device->model }}</td><td>{{ number_format($device->selling_price,2) }} {{ $device->currency }}</td><td class="capitalize">{{ $device->management_mode }}</td><td><span class="status-pill {{ $device->lock_status === 'locked' ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700' }}">{{ str_replace('_',' ',$device->status) }}</span></td><td>{{ $device->last_seen_at?->diffForHumans() ?? 'Never' }}</td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-slate-500">No devices registered yet.</td></tr>@endforelse
        </tbody></table></div>
    </section>
    @if(auth()->user()->isSuperAdmin())
    <div class="mt-7 grid gap-6 xl:grid-cols-2">
        <section class="panel"><div class="panel-header"><h2 class="section-title">Recent Shop Owners</h2><a class="text-sm font-bold text-indigo-600" href="{{ route('shops.index') }}">View all</a></div><div class="divide-y divide-slate-100">@forelse($recentShops as $shop)<a class="flex items-center justify-between p-5 hover:bg-slate-50" href="{{ route('shops.show',$shop) }}"><div><strong>{{ $shop->name }}</strong><p class="text-xs text-slate-500">{{ $shop->owner_name }}</p></div><span class="status-pill {{ $shop->status==='active'?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700' }}">{{ $shop->status }}</span></a>@empty<p class="p-5 text-slate-500">No Shop Owners yet.</p>@endforelse</div></section>
        <section class="panel"><div class="panel-header"><h2 class="section-title">Recent Commission Payments</h2><a class="text-sm font-bold text-indigo-600" href="{{ route('commissions.index') }}#record-settlement">View ledger</a></div><div class="divide-y divide-slate-100">@forelse($recentSettlements as $settlement)<div class="flex items-center justify-between p-5"><div><strong>{{ $settlement->shop->name }}</strong><p class="text-xs text-slate-500">{{ $settlement->settlement_number }} · {{ $settlement->payment_date->format('d M Y') }}</p></div><strong>LKR {{ number_format($settlement->amount,2) }}</strong></div>@empty<p class="p-5 text-slate-500">No commission payments yet.</p>@endforelse</div></section>
        <section class="panel"><div class="panel-header"><h2 class="section-title">Highest Outstanding Shop Balances</h2></div><div class="divide-y divide-slate-100">@forelse($topOutstandingShops as $shop)<div class="flex items-center justify-between p-5"><span>{{ $shop->name }}</span><strong class="text-red-700">LKR {{ number_format($shop->commissions_sum_outstanding_amount??0,2) }}</strong></div>@empty<p class="p-5 text-slate-500">No shop balances.</p>@endforelse</div></section>
        <section class="panel"><div class="panel-header"><h2 class="section-title">Recent SMS Failures</h2><a class="text-sm font-bold text-indigo-600" href="{{ route('sms.logs',['status'=>'failed']) }}">Open logs</a></div><div class="divide-y divide-slate-100">@forelse($recentSmsFailures as $sms)<div class="p-5"><div class="flex justify-between gap-3"><strong>{{ $sms->shop?->name??'Platform' }}</strong><span class="status-pill bg-red-50 text-red-700">failed</span></div><p class="mt-1 text-xs text-slate-500">{{ $sms->failure_reason }}</p></div>@empty<p class="p-5 text-slate-500">No SMS failures.</p>@endforelse</div></section>
    </div>
    @else
    <section class="panel mt-7"><div class="panel-header"><h2 class="section-title">Recent Payments</h2><a class="text-sm font-bold text-indigo-600" href="{{ route('payments.index') }}">View all</a></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Receipt</th><th>Customer</th><th>Device</th><th>Amount</th><th>Date</th></tr></thead><tbody>@forelse($recentPayments as $payment)<tr><td><a class="font-bold text-indigo-600" href="{{ route('payments.show',$payment) }}">{{ $payment->receipt_number }}</a></td><td>{{ $payment->customer->name }}</td><td>{{ $payment->device->brand }} {{ $payment->device->model }}</td><td>LKR {{ number_format($payment->amount,2) }}</td><td>{{ $payment->payment_date->format('d M Y') }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center">No payments yet.</td></tr>@endforelse</tbody></table></div></section>
    @endif
</x-layouts.app>
