<x-layouts.app title="Edit Setup Instruction">
<div class="mx-auto max-w-5xl">
    <a class="text-sm font-bold text-indigo-600" href="{{ route('setup-instructions.index',['computer_os'=>$instruction->computer_os,'phone_brand'=>$instruction->phone_brand]) }}">← Instruction list</a>
    <div class="mb-6 mt-4"><p class="eyebrow">{{ strtoupper($instruction->computer_os) }} · {{ \App\Services\SetupInstructionCatalog::BRANDS[$instruction->phone_brand] }}</p><h1 class="page-title">Edit step {{ $instruction->step_number }}</h1><p class="page-copy">All required sections are structured; one list item per line and error mappings as JSON objects.</p></div>
    <form method="post" enctype="multipart/form-data" action="{{ route('setup-instructions.update',$instruction) }}" class="panel space-y-6 p-6">@csrf @method('put')
        <div class="grid gap-5 md:grid-cols-2"><label class="field-label md:col-span-2">Title <x-required/><input class="field-input mt-1" name="title" value="{{ old('title',$instruction->title) }}" required></label><label class="field-label md:col-span-2">Short description <x-required/><textarea class="field-input mt-1" name="short_description" required>{{ old('short_description',$instruction->short_description) }}</textarea></label><label class="field-label md:col-span-2">Why required <x-required/><textarea class="field-input mt-1" name="why_required" required>{{ old('why_required',$instruction->why_required) }}</textarea></label><label class="field-label">Action location <x-required/><input class="field-input mt-1" name="action_location" value="{{ old('action_location',$instruction->action_location) }}" required></label><label class="field-label">Shell type<input class="field-input mt-1" name="shell_type" value="{{ old('shell_type',$instruction->shell_type) }}"></label></div>
        <label class="field-label">Numbered instructions — one per line <x-required/><textarea class="field-input mt-1 font-mono text-sm" rows="8" name="numbered_instructions_text" required>{{ old('numbered_instructions_text',implode("\n",$instruction->numbered_instructions)) }}</textarea></label>
        <div class="grid gap-5 md:grid-cols-2"><label class="field-label">Run from<input class="field-input mt-1" name="run_from" value="{{ old('run_from',$instruction->run_from) }}"></label><label class="field-label">Server check key<input class="field-input mt-1" name="server_check_key" value="{{ old('server_check_key',$instruction->server_check_key) }}"></label></div>
        <label class="field-label">Command<textarea class="field-input mt-1 font-mono text-sm" rows="7" name="command">{{ old('command',$instruction->command) }}</textarea></label>
        <label class="field-label">Terminal help<textarea class="field-input mt-1" name="terminal_help">{{ old('terminal_help',$instruction->terminal_help) }}</textarea></label>
        <label class="field-label">Expected output <x-required/><textarea class="field-input mt-1" rows="3" name="expected_output" required>{{ old('expected_output',$instruction->expected_output) }}</textarea></label>
        <label class="field-label">Possible errors JSON <x-required/><textarea class="field-input mt-1 font-mono text-xs" rows="12" name="possible_errors_json" required>{{ old('possible_errors_json',json_encode($instruction->possible_errors,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) }}</textarea><span class="mt-1 text-xs font-normal text-slate-500">Each object requires output, meaning, and solution.</span></label>
        <label class="field-label">Troubleshooting JSON <x-required/><textarea class="field-input mt-1 font-mono text-xs" rows="8" name="troubleshooting_json" required>{{ old('troubleshooting_json',json_encode($instruction->troubleshooting,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)) }}</textarea></label>
        <div class="grid gap-5 md:grid-cols-2"><label class="field-label">Verification items — one per line <x-required/><textarea class="field-input mt-1" rows="6" name="verification_items_text" required>{{ old('verification_items_text',implode("\n",$instruction->verification_items)) }}</textarea></label><label class="field-label">Required confirmation keys — one per line<textarea class="field-input mt-1" rows="6" name="confirmation_items_text">{{ old('confirmation_items_text',implode("\n",$instruction->confirmation_items ?: [])) }}</textarea></label></div>
        <label class="field-label">Reference screenshot<input class="field-input mt-1" type="file" name="screenshot" accept="image/*"></label>
        <label class="flex gap-2 text-sm font-semibold"><input type="checkbox" name="active" value="1" @checked(old('active',$instruction->active))> Active in technician wizard</label>
        <div class="flex justify-end"><button class="primary-button">Save structured instruction</button></div>
    </form>
</div>
</x-layouts.app>
