<x-layouts.app title="Register device">
    <div class="mx-auto max-w-5xl"><div class="mb-7"><p class="eyebrow">Enrollment</p><h1 class="page-title">Register a device</h1><p class="page-copy">Create the business record first, then activate the physical phone with the single-use code.</p></div>
    <form method="post" action="{{ route('devices.store') }}" class="space-y-6">@csrf
        <section class="panel p-6"><h2 class="section-title">Customer</h2><div class="form-grid mt-5"><label class="field-label">Full name<input class="field-input" name="customer_name" value="{{ old('customer_name') }}" required></label><label class="field-label">Phone number<input class="field-input" name="customer_phone" value="{{ old('customer_phone') }}" required></label><label class="field-label sm:col-span-2">Address (optional)<textarea class="field-input" name="customer_address" rows="2">{{ old('customer_address') }}</textarea></label></div></section>
        <section class="panel p-6"><h2 class="section-title">Device and sale</h2><div class="form-grid mt-5">
            <label class="field-label">Brand<input class="field-input" name="brand" value="{{ old('brand') }}" required></label><label class="field-label">Model<input class="field-input" name="model" value="{{ old('model') }}" required></label>
            <label class="field-label">IMEI<input class="field-input font-mono" name="imei" value="{{ old('imei') }}" inputmode="numeric" required></label><label class="field-label">Secondary IMEI<input class="field-input font-mono" name="secondary_imei" value="{{ old('secondary_imei') }}" inputmode="numeric"></label>
            <label class="field-label">Serial number<input class="field-input" name="serial_number" value="{{ old('serial_number') }}"></label><label class="field-label">Branch<input class="field-input" name="shop_branch" value="{{ old('shop_branch', auth()->user()->business_name) }}"></label>
            <label class="field-label">Selling price<input class="field-input" name="selling_price" value="{{ old('selling_price') }}" type="number" min="0" step="0.01" required></label><label class="field-label">Currency<select class="field-input" name="currency"><option>LKR</option><option>USD</option><option>EUR</option></select></label>
            <label class="field-label">Support phone<input class="field-input" name="support_phone" value="{{ old('support_phone', auth()->user()->phone) }}"></label><label class="field-label">Management mode<select class="field-input" name="management_mode"><option value="standard">Standard application mode</option><option value="managed">Managed device mode</option></select></label>
            <label class="sm:col-span-2 flex items-start gap-3 rounded-2xl bg-indigo-50 p-4 text-sm text-indigo-950"><input class="mt-1" type="checkbox" name="location_tracking_enabled" value="1" @checked(old('location_tracking_enabled'))><span><strong>Request authorized location tracking</strong><br>Android will still require visible user permission and a foreground-service notification for continuous tracking.</span></label>
            <label class="field-label sm:col-span-2">Notes<textarea class="field-input" name="notes" rows="3">{{ old('notes') }}</textarea></label>
        </div></section>
        <section class="panel p-6">
            <h2 class="section-title">Device Management PIN</h2>
            <p class="section-copy mt-1">This PIN protects management actions on the registered phone. Share it only with authorized staff or the device owner when required.</p>
            <div class="form-grid mt-5">
                <label class="field-label">Management PIN<input id="management-pin" class="field-input font-mono tracking-widest" type="password" name="management_pin" value="{{ old('management_pin') }}" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required autocomplete="new-password"></label>
                <label class="field-label">Confirm Management PIN<input id="management-pin-confirmation" class="field-input font-mono tracking-widest" type="password" name="management_pin_confirmation" value="{{ old('management_pin_confirmation') }}" inputmode="numeric" pattern="[0-9]{4}" maxlength="4" required autocomplete="new-password"></label>
            </div>
            <div class="mt-4 flex flex-wrap gap-3"><button id="toggle-management-pin" type="button" class="secondary-button">Show PIN</button><button id="generate-management-pin" type="button" class="secondary-button">Generate PIN</button><button id="copy-management-pin" type="button" class="secondary-button">Copy PIN</button></div>
        </section>
        <div class="flex justify-end gap-3"><a class="secondary-button" href="{{ route('devices.index') }}">Cancel</a><button class="primary-button">Register and create activation code</button></div>
    </form></div>
    <script>document.addEventListener('DOMContentLoaded',()=>{const p=document.getElementById('management-pin'),c=document.getElementById('management-pin-confirmation'),t=document.getElementById('toggle-management-pin');t.addEventListener('click',()=>{const show=p.type==='password';p.type=c.type=show?'text':'password';t.textContent=show?'Hide PIN':'Show PIN'});document.getElementById('generate-management-pin').addEventListener('click',()=>{let v;do{v=String(crypto.getRandomValues(new Uint32Array(1))[0]%10000).padStart(4,'0')}while(['0000','1111','1234','4321'].includes(v));p.value=c.value=v});document.getElementById('copy-management-pin').addEventListener('click',()=>{if(/^\d{4}$/.test(p.value))navigator.clipboard.writeText(p.value)})});</script>
</x-layouts.app>
