<x-layouts.app title="Devices">
<div class="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p class="eyebrow">Inventory</p><h1 class="page-title">{{ auth()->user()->isSuperAdmin() ? 'All devices' : 'My devices' }}</h1><p class="page-copy">Registered devices cannot be permanently deleted by normal Admins.</p></div><a class="primary-button" href="{{ route('devices.create') }}">+ Register device</a></div>
<section class="panel"><form class="panel-header flex-wrap" method="get"><input class="field-input max-w-md" name="search" value="{{ request('search') }}" placeholder="Search customer, brand, or model"><select class="field-input max-w-52" name="status"><option value="">All statuses</option>@foreach(['pending_activation','active_unlocked','locked','offline','permanently_released','demo'] as $status)<option @selected(request('status')===$status) value="{{ $status }}">{{ ucwords(str_replace('_',' ',$status)) }}</option>@endforeach</select><button class="secondary-button">Filter</button></form>
<div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Customer</th><th>Device</th><th>IMEI</th><th>Price</th><th>Added by</th><th>Mode</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($devices as $device)<tr><td><strong>{{ $device->customer->name }}</strong><br><small>{{ $device->customer->phone }}</small></td><td>@if(auth()->user()->isSuperAdmin()&&$device->status==='demo')<input form="bulk-demo-delete" type="checkbox" name="device_ids[]" value="{{ $device->id }}">@endif {{ $device->brand }} {{ $device->model }}</td><td>{{ $device->masked_imei }}</td><td>{{ number_format($device->selling_price,2) }} {{ $device->currency }}</td><td>{{ $device->admin->name }}</td><td>{{ $device->management_mode }}</td><td>{{ str_replace('_',' ',$device->status) }}</td><td><details><summary class="cursor-pointer font-semibold text-indigo-600">Actions</summary><div class="mt-2 w-72 space-y-2 rounded-xl border bg-white p-3 shadow"><a class="secondary-button block text-center" href="{{ route('devices.show',$device) }}">View</a>@can('update',$device)<a class="secondary-button block text-center" href="{{ route('devices.edit',$device) }}">Edit</a>@endcan @can('archive',$device)<form method="post" action="{{ route('devices.archive',$device) }}" class="space-y-2 rounded-lg border p-2">@csrf<p class="text-xs">Archive {{ $device->customer->name }} · {{ $device->brand }} {{ $device->model }} · {{ Str::upper(Str::substr($device->uuid,0,8)) }}<br>{{ $device->management_status }} / {{ $device->lock_status }}</p><input class="field-input" type="password" name="password" placeholder="Account password" required><button class="secondary-button w-full">Archive</button></form>@endcan @if(auth()->user()->isSuperAdmin())<form method="post" action="{{ route('devices.destroy',$device->id) }}" class="space-y-2 rounded-lg border border-red-200 p-2">@csrf @method('delete')<strong class="text-red-700">Permanently Delete</strong><textarea class="field-input" name="reason" placeholder="Deletion reason" required></textarea><input class="field-input" type="password" name="password" placeholder="Super Admin password" required><input class="field-input" name="confirmation" placeholder="Type DELETE" pattern="DELETE" required><label class="flex gap-2 text-xs"><input type="checkbox" name="confirmed" value="1" required> I understand this permanently removes the record.</label><button class="danger-button w-full">Delete permanently</button></form>@endif</div></details></td></tr>
@empty<tr><td colspan="8" class="py-12 text-center">No matching devices.</td></tr>@endforelse
</tbody></table></div><div class="p-5">{{ $devices->links() }}</div></section>
@if(auth()->user()->isSuperAdmin())<form id="bulk-demo-delete" method="post" action="{{ route('devices.demo.bulk-delete') }}" class="panel mt-6 space-y-3 p-5">@csrf @method('delete')<h2 class="section-title">Delete Demo Devices</h2><input class="field-input" name="reason" placeholder="Deletion reason" required><input class="field-input" type="password" name="password" placeholder="Super Admin password" required><input class="field-input" name="confirmation" placeholder="Type DELETE" pattern="DELETE" required><label class="flex gap-2"><input type="checkbox" name="confirmed" value="1" required> Permanently remove selected demo records.</label><button class="danger-button">Delete selected demo devices</button></form>@endif
</x-layouts.app>
