<x-layouts.app :title="$device->brand.' '.$device->model">
    <div class="mb-7 flex flex-wrap items-start justify-between gap-5"><div><a class="mb-3 inline-block text-sm font-semibold text-indigo-600" href="{{ route('devices.index') }}">← Devices</a><h1 class="page-title">{{ $device->brand }} {{ $device->model }}</h1><p class="page-copy">{{ $device->customer->name }} · Ref {{ Str::upper(Str::substr($device->uuid,0,8)) }}</p></div><span class="status-pill {{ $device->lock_status === 'locked' ? 'bg-red-50 text-red-700' : 'bg-emerald-50 text-emerald-700' }}">{{ ucwords(str_replace('_',' ',$device->status)) }}</span></div>
    @if(session('activation_code'))<section class="mb-6 rounded-3xl border border-indigo-200 bg-indigo-50 p-6"><p class="eyebrow">Single-use activation code</p><p class="mt-2 font-mono text-3xl font-black tracking-widest text-indigo-950">{{ session('activation_code') }}</p><p class="mt-2 text-sm text-indigo-800">Expires in 24 hours and is displayed only now. Enter it in the Android app.</p></section>@endif
    @if(session('unlock_code'))<section class="mb-6 rounded-3xl border border-emerald-200 bg-emerald-50 p-6"><p class="eyebrow">One-time temporary unlock code</p><p class="mt-2 font-mono text-3xl font-black tracking-widest text-emerald-950">{{ session('unlock_code') }}</p><p class="mt-2 text-sm text-emerald-800">Expires in 30 minutes, allows five attempts, and is displayed only now.</p></section>@endif
    @include('devices._qr-generator')
    <div class="grid gap-6 xl:grid-cols-[1.5fr_1fr]">
        <div class="space-y-6"><section class="panel p-6"><h2 class="section-title">Overview</h2><dl class="details-grid mt-5"><div><dt>Customer</dt><dd>{{ $device->customer->name }}</dd></div><div><dt>Contact</dt><dd>{{ $device->customer->phone }}</dd></div><div><dt>IMEI</dt><dd class="font-mono">{{ $device->masked_imei }}</dd></div><div><dt>Selling price</dt><dd>{{ number_format($device->selling_price,2) }} {{ $device->currency }}</dd></div><div><dt>Added by</dt><dd>{{ $device->admin->name }}</dd></div><div><dt>Last online</dt><dd>{{ $device->last_seen_at?->diffForHumans() ?? 'Never' }}</dd></div></dl></section>
        <section class="panel p-6"><div class="panel-header !p-0"><div><h2 class="section-title">Capabilities</h2><p class="section-copy">Reported by the enrolled Android phone—not inferred from registration.</p></div></div>@unless($device->is_device_owner)<div class="mt-4 rounded-2xl bg-amber-50 p-4 text-sm text-amber-900"><strong>Device Owner setup required.</strong> This phone is registered in Standard Mode. Full lock, uninstall protection, and reset restriction are unavailable.</div>@endunless<div class="mt-5 grid gap-3 sm:grid-cols-2">@foreach(['Managed mode'=>$device->management_mode==='managed' && $device->is_device_owner,'Device owner'=>$device->is_device_owner,'Admin active'=>$device->is_admin_active,'Uninstall restriction'=>$device->can_block_uninstall,'Reset restriction'=>$device->can_block_reset,'Lock task permitted'=>$device->is_lock_task_permitted,'Full device lock'=>$device->can_full_lock,'Location permission'=>$device->location_permission_status==='granted','Background location'=>$device->background_location_permission_status==='granted','GPS enabled'=>$device->gps_status==='enabled'] as $label=>$ok)<div class="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm"><span>{{ $label }}</span><strong class="{{ $ok ? 'text-emerald-600':'text-slate-400' }}">{{ $ok ? 'Yes':'No' }}</strong></div>@endforeach</div></section>
        <section class="panel"><div class="panel-header"><div><h2 class="section-title">Command history</h2><p class="section-copy">Pending, dispatched, delivered, executing, and completed states are tracked separately.</p></div></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Command</th><th>Status</th><th>Result</th><th>Requested by</th><th>Time</th></tr></thead><tbody>@forelse($device->commands->sortByDesc('created_at') as $command)<tr><td>{{ str_replace('_',' ',$command->type) }}</td><td><span class="status-pill {{ $command->status === 'failed' ? 'bg-red-50 text-red-700':'bg-slate-100 text-slate-700' }}">{{ $command->status }}</span></td><td><p>{{ $command->result_message ?: '—' }}</p>@if($command->failure_code)<p class="text-xs font-bold text-red-600">{{ $command->failure_code }}</p>@endif @if($command->firebase_error)<p class="mt-1 text-xs text-red-600">Firebase: {{ $command->firebase_error }}</p>@elseif($command->firebase_message_id)<p class="mt-1 text-xs text-emerald-700">Firebase dispatched</p>@endif</td><td>{{ $command->requester?->name ?? 'System' }}</td><td>{{ $command->created_at->diffForHumans() }}</td></tr>@empty<tr><td colspan="5" class="py-8 text-center text-slate-500">No commands yet.</td></tr>@endforelse</tbody></table></div></section></div>
        <aside class="space-y-6"><section class="panel p-6"><h2 class="section-title">Device control</h2><p class="section-copy mt-1">Commands are signed, expire automatically, and need phone confirmation.</p><div class="mt-5 grid gap-3">
            @foreach([['LOCK_DEVICE','Lock device','danger-button'],['UNLOCK_DEVICE','Temporarily unlock','primary-button'],['REQUEST_LOCATION','Request current location','secondary-button'],['SYNC_DEVICE','Sync device','secondary-button']] as [$type,$label,$class])
                @if($type === 'SYNC_DEVICE')<form method="post" action="{{ route('devices.command',$device) }}">@csrf<input type="hidden" name="type" value="{{ $type }}"><button class="{{ $class }} w-full" @disabled($device->isReleased())>{{ $label }}</button></form>
                @else<details class="rounded-xl border border-slate-200 p-3"><summary class="cursor-pointer text-sm font-bold">{{ $label }}</summary><form class="mt-3 space-y-3" method="post" action="{{ route('devices.command',$device) }}">@csrf<input type="hidden" name="type" value="{{ $type }}"><label class="field-label">Reason<input class="field-input" name="reason" required></label><label class="field-label">Current password<input class="field-input" type="password" name="password" required autocomplete="current-password"></label><button class="{{ $class }} w-full" @disabled($device->isReleased() || ($type === 'LOCK_DEVICE' && ! $device->can_full_lock))>Confirm {{ strtolower($label) }}</button>@if($type === 'LOCK_DEVICE' && ! $device->can_full_lock)<p class="text-xs text-amber-700">Device Owner provisioning and a successful capability sync are required.</p>@endif</form></details>@endif
            @endforeach
        </div></section>
        <section class="panel p-6">
            <h2 class="section-title">Device Management PIN</h2>
            <p id="revealed-management-pin" data-pin="{{ session('revealed_management_pin') }}" class="mt-3 font-mono text-3xl font-black tracking-[.35em]">{{ session()->has('revealed_management_pin') ? session('revealed_management_pin') : '••••' }}</p>
            <dl class="details-grid mt-5"><div><dt>PIN configured</dt><dd>{{ $device->management_pin_hash ? 'Yes' : 'No' }}</dd></div><div><dt>Last changed</dt><dd>{{ $device->management_pin_changed_at?->format('Y-m-d H:i') ?? 'Never' }}</dd></div><div><dt>Changed by</dt><dd>{{ $device->managementPinChangedBy?->name ?? '—' }}</dd></div><div><dt>Failed phone attempts</dt><dd>{{ $device->management_pin_failed_attempts }}</dd></div>@if($device->management_pin_locked_until)<div><dt>Locked until</dt><dd>{{ $device->management_pin_locked_until->format('Y-m-d H:i') }}</dd></div>@endif</dl>
            <div class="mt-5 grid gap-3">
                <details class="rounded-xl border p-3"><summary class="cursor-pointer font-semibold">Reveal PIN</summary><form class="mt-3 space-y-3" method="post" action="{{ route('devices.management-pin.reveal',$device) }}">@csrf<label class="field-label">Account password<input class="field-input" type="password" name="password" required autocomplete="current-password"></label><button class="primary-button w-full">Reveal for 30 seconds</button></form></details>
                <button id="copy-revealed-management-pin" type="button" class="secondary-button w-full" @disabled(!session()->has('revealed_management_pin'))>Copy revealed PIN</button>
                <details class="rounded-xl border p-3"><summary class="cursor-pointer font-semibold">Change PIN</summary><form class="mt-3 space-y-3" method="post" action="{{ route('devices.management-pin.change',$device) }}">@csrf<label class="field-label">Account password<input class="field-input" type="password" name="password" required></label><label class="field-label">New 4-digit PIN<input class="field-input" type="password" name="management_pin" inputmode="numeric" maxlength="4" required></label><label class="field-label">Confirm PIN<input class="field-input" type="password" name="management_pin_confirmation" inputmode="numeric" maxlength="4" required></label><button class="primary-button w-full">Change PIN</button></form></details>
                <details class="rounded-xl border p-3"><summary class="cursor-pointer font-semibold">Generate New PIN</summary><form class="mt-3 space-y-3" method="post" action="{{ route('devices.management-pin.generate',$device) }}">@csrf<label class="field-label">Account password<input class="field-input" type="password" name="password" required></label><button class="primary-button w-full">Generate securely</button></form></details>
                @if(auth()->user()->isSuperAdmin())<form method="post" action="{{ route('devices.management-pin.reset-attempts',$device) }}">@csrf<label class="field-label">Account password<input class="field-input" type="password" name="password" required></label><button class="secondary-button mt-2 w-full">Reset Failed Attempts</button></form>@endif
            </div>
        </section>
        @if(auth()->user()->isSuperAdmin())<section class="panel p-6"><h2 class="section-title">Delivery diagnostics</h2><dl class="details-grid mt-4"><div><dt>Queue connection</dt><dd>{{ $queueDiagnostics['connection'] }}</dd></div><div><dt>Pending queue jobs</dt><dd>{{ $queueDiagnostics['pending_jobs'] }}</dd></div><div class="sm:col-span-2"><dt>Last Firebase result</dt><dd>{{ $queueDiagnostics['last_firebase_result']?->firebase_error ?: ($queueDiagnostics['last_firebase_result']?->firebase_message_id ? 'Dispatched successfully' : 'No Firebase attempt recorded') }}</dd></div></dl><p class="mt-3 text-xs text-slate-500">Shared hosting should use QUEUE_CONNECTION=sync. The 15-minute queue cron is fallback only.</p></section>@endif
        <section class="panel p-6"><h2 class="section-title">Temporary unlock code</h2><p class="section-copy">Generate a single-use code after confirming your password.</p><form class="mt-4 space-y-3" method="post" action="{{ route('devices.unlock-code',$device) }}">@csrf<label class="field-label">Current password<input class="field-input" type="password" name="password" required autocomplete="current-password"></label><button class="secondary-button w-full" @disabled($device->isReleased())>Generate one-time code</button></form></section>
        <section class="panel border-red-100 p-6"><h2 class="section-title text-red-900">Permanent release</h2><p class="mt-2 text-sm text-slate-600">Permanently removes management restrictions after the phone confirms. The device cannot be locked or tracked again without re-enrollment.</p><details class="mt-4"><summary class="cursor-pointer text-sm font-semibold text-red-700">Continue with release</summary><form class="mt-4 space-y-3" method="post" action="{{ route('devices.release',$device) }}">@csrf<label class="field-label">Release reason<textarea class="field-input" name="reason" required></textarea></label><label class="field-label">Your password<input class="field-input" type="password" name="password" required></label><label class="flex gap-2 text-sm"><input type="checkbox" name="confirmed" value="1" required> I understand this is permanent.</label><button class="danger-button w-full">Permanently release</button></form></details></section></aside>
    </div>
    <script>document.addEventListener('DOMContentLoaded',()=>{const value=document.getElementById('revealed-management-pin'),copy=document.getElementById('copy-revealed-management-pin');if(value.dataset.pin){const pin=value.dataset.pin;copy.addEventListener('click',()=>navigator.clipboard.writeText(pin));setTimeout(()=>{value.textContent='••••';value.dataset.pin='';copy.disabled=true},30000)}});</script>
</x-layouts.app>
