<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\DeviceManagementPinController;
use App\Http\Controllers\DeviceProvisioningController;
use App\Http\Controllers\DeviceLifecycleController;
use App\Http\Controllers\QrProvisioningSettingsController;
use App\Http\Controllers\OfflineProtectionSettingsController;
use App\Http\Controllers\DeviceOfflineProtectionController;
use App\Http\Controllers\OfflineProtectionReportController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ShopUserController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerPaymentController;
use App\Http\Controllers\PlatformCommissionController;
use App\Http\Controllers\DeviceSetupController;
use App\Http\Controllers\SetupInstructionController;
use App\Http\Controllers\SmsSettingsController;
use App\Http\Controllers\BusinessReportController;
use App\Http\Controllers\PhoneBrandController;
use App\Http\Controllers\SystemSettingsController;
use App\Http\Controllers\AuditLogController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'create'])->name('login');
    Route::post('/login', [AuthController::class, 'store'])->middleware('throttle:5,1');
});
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::resource('devices', DeviceController::class)->only(['index', 'create', 'store', 'show', 'edit', 'update']);
    Route::post('/devices/{device}/archive', [DeviceLifecycleController::class, 'archive'])->middleware('throttle:5,1')->name('devices.archive');
    Route::delete('/devices/{device}', [DeviceLifecycleController::class, 'destroy'])->middleware('throttle:5,1')->name('devices.destroy');
    Route::delete('/devices/{device}/force-delete', [DeviceLifecycleController::class, 'forceDestroy'])->middleware('throttle:5,1')->name('devices.force-delete');
    Route::get('/archived-devices', [DeviceLifecycleController::class, 'archived'])->name('devices.archived');
    Route::post('/archived-devices/{device}/restore', [DeviceLifecycleController::class, 'restore'])->middleware('throttle:5,1')->name('devices.restore');
    Route::delete('/devices/bulk', [DeviceLifecycleController::class, 'bulkDelete'])->middleware('throttle:3,1')->name('devices.bulk-delete');
    Route::post('/devices/{device}/commands', [DeviceController::class, 'command'])->middleware('throttle:5,1')->name('devices.command');
    Route::post('/devices/{device}/release', [DeviceController::class, 'release'])->middleware('throttle:5,1')->name('devices.release');
    Route::put('/devices/{device}/offline-protection', [DeviceOfflineProtectionController::class, 'update'])->name('devices.offline-protection.update');
    Route::post('/devices/{device}/offline-protection/refresh', [DeviceOfflineProtectionController::class, 'refresh'])->name('devices.offline-protection.refresh');
    Route::post('/devices/{device}/offline-protection/recalculate', [DeviceOfflineProtectionController::class, 'recalculate'])->name('devices.offline-protection.recalculate');
    Route::post('/devices/{device}/unlock-code', [DeviceController::class, 'generateUnlockCode'])->middleware('throttle:5,1')->name('devices.unlock-code');
    Route::post('/devices/{device}/management-pin/reveal', [DeviceManagementPinController::class, 'reveal'])->middleware('throttle:5,1')->name('devices.management-pin.reveal');
    Route::post('/devices/{device}/management-pin/change', [DeviceManagementPinController::class, 'change'])->middleware('throttle:5,1')->name('devices.management-pin.change');
    Route::post('/devices/{device}/management-pin/generate', [DeviceManagementPinController::class, 'generate'])->middleware('throttle:5,1')->name('devices.management-pin.generate');
    Route::post('/devices/{device}/management-pin/reset-attempts', [DeviceManagementPinController::class, 'resetAttempts'])->middleware('throttle:5,1')->name('devices.management-pin.reset-attempts');
    Route::post('/devices/{device}/provisioning', [DeviceProvisioningController::class, 'generate'])->middleware('throttle:5,1')->name('devices.provisioning.generate');
    Route::get('/devices/{device}/provisioning/{token}', [DeviceProvisioningController::class, 'show'])->name('devices.provisioning.show');
    Route::get('/devices/{device}/provisioning/{token}/image', [DeviceProvisioningController::class, 'image'])->name('devices.provisioning.image');
    Route::post('/devices/{device}/provisioning/{token}/revoke', [DeviceProvisioningController::class, 'revoke'])->name('devices.provisioning.revoke');
    Route::get('/settings/qr-provisioning', [QrProvisioningSettingsController::class, 'edit'])->name('settings.qr-provisioning');
    Route::put('/settings/qr-provisioning', [QrProvisioningSettingsController::class, 'update'])->name('settings.qr-provisioning.update');
    Route::post('/settings/qr-provisioning/validate', [QrProvisioningSettingsController::class, 'validateConfiguration'])->name('settings.qr-provisioning.validate');
    Route::get('/settings/offline-protection', [OfflineProtectionSettingsController::class, 'edit'])->name('settings.offline-protection');
    Route::put('/settings/offline-protection', [OfflineProtectionSettingsController::class, 'update'])->name('settings.offline-protection.update');
    Route::get('/reports/offline-protection', OfflineProtectionReportController::class)->name('reports.offline-protection');
    Route::resource('shops', ShopController::class)->except(['destroy']);
    Route::post('/shops/{shop}/archive', [ShopController::class,'archive'])->name('shops.archive');
    Route::post('/archived-shops/{shop}/restore', [ShopController::class,'restore'])->name('shops.restore');
    Route::delete('/archived-shops/{shop}', [ShopController::class,'destroy'])->name('shops.destroy-permanently');
    Route::post('/shops/{shop}/recalculate-commission', [ShopController::class,'recalculate'])->name('shops.recalculate-commission');
    Route::post('/shops/{shop}/status', [ShopController::class,'status'])->middleware('throttle:5,1')->name('shops.status');
    Route::post('/shops/{shop}/reset-password', [ShopController::class,'resetPassword'])->middleware('throttle:5,1')->name('shops.reset-password');
    Route::get('/my-shop/profile', [ShopController::class,'profile'])->name('shop-profile.edit');
    Route::put('/my-shop/profile', [ShopController::class,'updateProfile'])->name('shop-profile.update');
    Route::get('/shop-users', [ShopUserController::class,'index'])->name('shop-users.index');
    Route::post('/shop-users', [ShopUserController::class,'store'])->name('shop-users.store');
    Route::patch('/shop-users/{shopUser}', [ShopUserController::class,'update'])->name('shop-users.update');
    Route::resource('customers', CustomerController::class);
    Route::get('/payments', [CustomerPaymentController::class,'index'])->name('payments.index');
    Route::get('/payments/create', [CustomerPaymentController::class,'create'])->name('payments.create');
    Route::post('/payments', [CustomerPaymentController::class,'store'])->name('payments.store');
    Route::get('/payments/{payment}', [CustomerPaymentController::class,'show'])->name('payments.show');
    Route::post('/payments/{payment}/reverse', [CustomerPaymentController::class,'reverse'])->name('payments.reverse');
    Route::get('/platform-commission', [PlatformCommissionController::class,'index'])->name('commissions.index');
    Route::post('/platform-settlements', [PlatformCommissionController::class,'settlement'])->name('settlements.store');
    Route::post('/platform-settlements/{settlement}/reverse', [PlatformCommissionController::class,'reverse'])->name('settlements.reverse');
    Route::post('/devices/{device}/setup', [DeviceSetupController::class,'start'])->name('setup.start');
    Route::get('/device-setup', [DeviceSetupController::class,'index'])->name('setup.index');
    Route::get('/setup/{setup}', [DeviceSetupController::class,'show'])->name('setup.show');
    Route::post('/setup/{setup}/step', [DeviceSetupController::class,'step'])->name('setup.step');
    Route::get('/setup/{setup}/helper/{os}', [DeviceSetupController::class,'helper'])->middleware('signed')->name('setup.helper');
    Route::get('/settings/setup-instructions', [SetupInstructionController::class, 'index'])->name('setup-instructions.index');
    Route::post('/settings/setup-instructions/sync', [SetupInstructionController::class, 'sync'])->name('setup-instructions.sync');
    Route::get('/settings/setup-instructions/{instruction}/edit', [SetupInstructionController::class, 'edit'])->name('setup-instructions.edit');
    Route::put('/settings/setup-instructions/{instruction}', [SetupInstructionController::class, 'update'])->name('setup-instructions.update');
    Route::get('/settings/sms', [SmsSettingsController::class,'edit'])->name('settings.sms');
    Route::get('/communication/sms-logs', [SmsSettingsController::class,'logs'])->name('sms.logs');
    Route::put('/settings/sms', [SmsSettingsController::class,'update'])->name('settings.sms.update');
    Route::post('/settings/sms/test', [SmsSettingsController::class,'test'])->middleware('throttle:5,1')->name('settings.sms.test');
    Route::post('/settings/sms/test-connection', [SmsSettingsController::class,'connection'])->middleware('throttle:5,1')->name('settings.sms.connection');
    Route::post('/sms-logs/{smsLog}/retry', [SmsSettingsController::class,'retry'])->name('sms.retry');
    Route::get('/business-reports/{type}', BusinessReportController::class)->name('reports.business');
    Route::resource('phone-brands', PhoneBrandController::class)->only(['index','store','update','destroy']);
    Route::get('/settings/system/{section}', [SystemSettingsController::class,'edit'])->name('settings.system');
    Route::put('/settings/system/{section}', [SystemSettingsController::class,'update'])->name('settings.system.update');
    Route::get('/settings/audit-logs', AuditLogController::class)->name('settings.audit-logs');
    Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
});
