<?php
namespace Tests\Feature;
use App\Models\Customer;use App\Models\Device;use App\Models\Shop;use App\Models\SystemSetting;use App\Models\User;use App\Services\CommissionService;use App\Services\CustomerPaymentService;use App\Services\FinancingService;use App\Services\SettlementService;use App\Services\Sms\TextItSmsService;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\Client\ConnectionException;use Illuminate\Support\Facades\Crypt;use Illuminate\Support\Facades\Http;use Illuminate\Support\Str;use Tests\TestCase;
class MultiShopFinancingTest extends TestCase{
 use RefreshDatabase;
 private function super(){return User::create(['name'=>'Platform Owner','email'=>uniqid().'@example.com','password'=>'Password@123','role'=>'super_admin','is_active'=>true]);}
 private function tenant(string $name='Shop A',float $rate=5):array{$shop=Shop::create(['name'=>$name,'owner_name'=>'Owner','email'=>uniqid().'@shop.test','mobile'=>'0770000000','address'=>'Address','reference_code'=>strtoupper(Str::random(8)),'commission_percentage'=>$rate,'commission_basis'=>'selling_price_percentage']);$user=User::create(['shop_id'=>$shop->id,'name'=>'Owner','email'=>uniqid().'@user.test','password'=>'Password@123','role'=>'shop_owner','is_active'=>true]);return[$shop,$user];}
 private function device(Shop $shop,User $user,float $price=100000):Device{$c=Customer::create(['shop_id'=>$shop->id,'admin_id'=>$user->id,'created_by'=>$user->id,'name'=>'Customer','phone'=>'0771111111','address'=>'Address']);return Device::create(['shop_id'=>$shop->id,'admin_id'=>$user->id,'customer_id'=>$c->id,'brand'=>'Samsung','model'=>'A15','imei'=>(string)random_int(100000000000000,999999999999999),'selling_price'=>$price,'currency'=>'LKR','status'=>'active_unlocked']);}
 public function test_super_admin_creates_separate_shop_owner_login(){ $s=$this->super();$this->actingAs($s)->post(route('shops.store'),['name'=>'ABC Mobile','owner_name'=>'Ali','email'=>'ali@abc.test','mobile'=>'0771234567','address'=>'Colombo','commission_percentage'=>5,'commission_basis'=>'selling_price_percentage','status'=>'active','temporary_password'=>'Temporary@123'])->assertRedirect();$this->assertDatabaseHas('shops',['name'=>'ABC Mobile']);$this->assertDatabaseHas('users',['email'=>'ali@abc.test','role'=>'shop_owner']);}
 public function test_shop_owner_cannot_access_another_shops_customer_or_device(){[$a,$ua]=$this->tenant('A');[$b,$ub]=$this->tenant('B');$d=$this->device($a,$ua);$this->actingAs($ub)->get(route('devices.show',$d))->assertForbidden();$this->actingAs($ub)->get(route('customers.show',$d->customer))->assertForbidden();}
 public function test_financing_balance_schedule_and_final_rounding_adjustment(){[$s,$u]=$this->tenant();$d=$this->device($s,$u,100000);$f=app(FinancingService::class)->create($d,['selling_price'=>100000,'first_payment'=>20000,'number_of_installments'=>3,'first_due_date'=>'2026-08-30','payment_frequency'=>'monthly','installment_amount'=>26666.67]);$this->assertSame('80000.00',$f->financed_balance);$this->assertCount(3,$f->installments);$this->assertSame(80000.0,round($f->installments->sum('expected_amount'),2));$this->assertSame('26666.66',$f->installments->last()->expected_amount);}
 public function test_selling_price_stays_authoritative_and_final_installment_collects_the_exact_balance(){[$s,$u]=$this->tenant();$d=$this->device($s,$u,45000);$f=app(FinancingService::class)->create($d,['selling_price'=>46999.99,'first_payment'=>10000,'number_of_installments'=>3,'first_due_date'=>'2026-09-01','payment_frequency'=>'monthly','installment_amount'=>10000]);$this->assertSame('45000.00',$d->fresh()->selling_price);$this->assertSame('45000.00',$f->selling_price);$this->assertSame('35000.00',$f->financed_balance);$this->assertSame(['10000.00','10000.00','15000.00'],$f->installments->pluck('expected_amount')->all());$this->assertSame(35000.0,round($f->installments->sum('expected_amount'),2));$this->assertSame(45000.0,round((float)$f->first_payment+$f->installments->sum('expected_amount'),2));}
 public function test_device_commission_is_snapshot_and_survives_shop_rate_change(){[$s,$u]=$this->tenant('A',5);$d=$this->device($s,$u);$c=app(CommissionService::class)->snapshot($d,$s,80000);$s->update(['commission_percentage'=>9]);$this->assertSame('5.0000',$c->fresh()->captured_percentage);$this->assertSame('5000.00',$c->commission_amount);}
 public function test_partial_customer_payment_allocates_oldest_installment(){[$s,$u]=$this->tenant();$d=$this->device($s,$u);app(FinancingService::class)->create($d,['selling_price'=>100000,'first_payment'=>20000,'number_of_installments'=>4,'first_due_date'=>'2026-08-30','payment_frequency'=>'monthly','installment_amount'=>20000]);$p=app(CustomerPaymentService::class)->receive(['idempotency_key'=>(string)Str::uuid(),'device_id'=>$d->id,'amount'=>10000,'payment_date'=>'2026-08-30','payment_method'=>'cash','send_sms'=>false],$u);$this->assertSame('10000.00',$p->amount);$this->assertSame('partially_paid',$d->financing->installments()->first()->fresh()->status);$this->assertSame('70000.00',$d->financing->fresh()->remaining_balance);}
 public function test_duplicate_payment_idempotency_key_does_not_double_charge(){[$s,$u]=$this->tenant();$d=$this->device($s,$u);app(FinancingService::class)->create($d,['selling_price'=>100000,'first_payment'=>0,'number_of_installments'=>2,'first_due_date'=>'2026-08-30','payment_frequency'=>'monthly','installment_amount'=>50000]);$key=(string)Str::uuid();$data=['idempotency_key'=>$key,'device_id'=>$d->id,'amount'=>5000,'payment_date'=>'2026-08-30','payment_method'=>'cash','send_sms'=>false];$a=app(CustomerPaymentService::class)->receive($data,$u);$b=app(CustomerPaymentService::class)->receive($data,$u);$this->assertSame($a->id,$b->id);$this->assertDatabaseCount('customer_payments',1);}
 public function test_sms_failure_does_not_reverse_financial_payment(){[$s,$u]=$this->tenant();$d=$this->device($s,$u);app(FinancingService::class)->create($d,['selling_price'=>100000,'first_payment'=>0,'number_of_installments'=>2,'first_due_date'=>'2026-08-30','payment_frequency'=>'monthly','installment_amount'=>50000]);$p=app(CustomerPaymentService::class)->receive(['idempotency_key'=>(string)Str::uuid(),'device_id'=>$d->id,'amount'=>5000,'payment_date'=>'2026-08-30','payment_method'=>'cash','send_sms'=>true],$u);$this->assertSame('completed',$p->status);$this->assertDatabaseHas('sms_logs',['device_id'=>$d->id,'sent_status'=>'failed']);}
 public function test_partial_platform_settlement_reduces_outstanding(){[$s,$u]=$this->tenant();$d=$this->device($s,$u);$c=app(CommissionService::class)->snapshot($d,$s,80000);$settlement=app(SettlementService::class)->record($s,['amount'=>2000,'payment_date'=>'2026-07-29','payment_method'=>'bank_transfer','allocation_method'=>'oldest_first'],$this->super());$this->assertSame('2000.00',$settlement->amount);$this->assertSame('3000.00',$c->fresh()->outstanding_amount);$this->assertSame('partially_paid',$c->fresh()->status);}
 public function test_required_markers_and_information_tooltips_are_rendered(){[$s,$u]=$this->tenant();$this->actingAs($u)->get(route('devices.create'))->assertOk()->assertSee('aria-label="required"',false)->assertSee('maximum permitted time the device may remain',false);}
 public function test_setup_wizard_is_tenant_scoped_and_resumable(){[$a,$ua]=$this->tenant('A');[$b,$ub]=$this->tenant('B');$d=$this->device($a,$ua);$response=$this->actingAs($ua)->post(route('setup.start',$d),['computer_os'=>'macos','brand_group'=>'samsung','authorized'=>1]);$response->assertRedirect();$setup=$d->setupSessions()->first();$this->actingAs($ub)->get(route('setup.show',$setup))->assertForbidden();$this->actingAs($ua)->get(route('setup.show',$setup))->assertOk()->assertSee('Download authenticated macOS shell helper');}
 public function test_staff_permissions_allow_only_selected_financial_actions(){[$shop,$owner]=$this->tenant();$staff=User::create(['shop_id'=>$shop->id,'name'=>'Collector','email'=>uniqid().'@staff.test','password'=>'Password@123','role'=>'shop_staff','staff_role'=>'payment_collector','shop_permissions'=>['payments.create'],'is_active'=>true]);$this->actingAs($staff)->get(route('payments.create'))->assertOk();$this->actingAs($staff)->get(route('customers.create'))->assertForbidden();$this->actingAs($staff)->get(route('shop-users.index'))->assertForbidden();}
 public function test_tenant_csv_report_never_contains_another_shops_customer(){[$a,$ua]=$this->tenant('A');[$b,$ub]=$this->tenant('B');Customer::create(['shop_id'=>$a->id,'admin_id'=>$ua->id,'created_by'=>$ua->id,'name'=>'Visible Customer','phone'=>'0771111111','address'=>'A']);Customer::create(['shop_id'=>$b->id,'admin_id'=>$ub->id,'created_by'=>$ub->id,'name'=>'Hidden Customer','phone'=>'0772222222','address'=>'B']);$response=$this->actingAs($ua)->get(route('reports.business',['type'=>'customers','format'=>'csv']))->assertOk();$csv=$response->streamedContent();$this->assertStringContainsString('Visible Customer',$csv);$this->assertStringNotContainsString('Hidden Customer',$csv);}
 public function test_settlement_reversal_restores_commission_outstanding_and_is_immutable(){[$shop,$owner]=$this->tenant();$device=$this->device($shop,$owner);$commission=app(CommissionService::class)->snapshot($device,$shop,80000);$super=$this->super();$settlement=app(SettlementService::class)->record($shop,['amount'=>2000,'payment_date'=>'2026-07-29','payment_method'=>'bank_transfer','allocation_method'=>'oldest_first'],$super);app(SettlementService::class)->reverse($settlement->load('allocations'),$super,'Bank transfer returned');$this->assertSame('5000.00',$commission->fresh()->outstanding_amount);$this->assertSame('reversed',$settlement->fresh()->status);$this->assertDatabaseHas('platform_settlement_reversals',['platform_settlement_id'=>$settlement->id,'reason'=>'Bank transfer returned']);}
 public function test_manual_settlement_cannot_allocate_another_shops_commission(){[$a,$ua]=$this->tenant('A');[$b,$ub]=$this->tenant('B');$foreign=app(CommissionService::class)->snapshot($this->device($b,$ub),$b,80000);$this->expectException(\Illuminate\Validation\ValidationException::class);app(SettlementService::class)->record($a,['amount'=>1000,'payment_date'=>'2026-07-29','payment_method'=>'cash','allocation_method'=>'manual','device_commission_id'=>$foreign->id],$this->super());}
 public function test_super_admin_sidebar_contains_every_required_module(){ $response=$this->actingAs($this->super())->get(route('dashboard'))->assertOk();foreach(['All Shop Owners','Add Shop Owner','Active Shops','Inactive Shops','Archived Shops','All Devices','Register Device','Archived Devices','Device Setup Wizard','Shop Commission','Shop Balances','Commission Payments','Commission Report','SMS Logs','SMS Templates','Offline Protection','Offline Report','General Settings','Commission Settings','SMS Gateway Settings','Device Settings','APK & Provisioning','Phone Brands','Setup Instructions','User Roles & Permissions','Audit Logs'] as $label)$response->assertSee($label,false);}
 public function test_shop_owner_sidebar_hides_super_admin_settings(){[$shop,$owner]=$this->tenant();$this->actingAs($owner)->get(route('dashboard'))->assertOk()->assertSee('My Customers')->assertSee('My Devices')->assertSee('Platform Commission')->assertDontSee('All Shop Owners')->assertDontSee('SMS Gateway Settings')->assertDontSee('User Roles & Permissions')->assertDontSee('Audit Logs');$this->actingAs($owner)->get(route('settings.system','general'))->assertForbidden();$this->actingAs($owner)->get(route('settings.audit-logs'))->assertForbidden();}
 public function test_inactive_shop_cannot_login_or_register_new_device(){[$shop,$owner]=$this->tenant();$shop->update(['status'=>'inactive']);$this->post('/login',['email'=>$owner->email,'password'=>'Password@123'])->assertSessionHasErrors('email');$this->actingAs($owner)->get(route('devices.create'))->assertForbidden();}
 public function test_every_super_admin_sidebar_destination_opens(){ $this->actingAs($this->super());foreach([route('shops.index'),route('shops.create'),route('shops.index',['status'=>'active']),route('shops.index',['status'=>'inactive']),route('shops.index',['status'=>'archived']),route('devices.index'),route('devices.create'),route('devices.archived'),route('setup.index'),route('commissions.index'),route('reports.business','commissions'),route('sms.logs'),route('settings.sms'),route('settings.offline-protection'),route('reports.offline-protection'),route('settings.system','general'),route('settings.system','commission'),route('settings.system','device'),route('settings.qr-provisioning'),route('phone-brands.index'),route('settings.system','setup-instructions'),route('settings.system','roles'),route('settings.audit-logs')] as $url)$this->get($url)->assertOk();}
 public function test_textit_request_uses_required_headers_payload_and_normalized_number(){SystemSetting::create(['key'=>'sms_enabled','value'=>'true','type'=>'boolean']);SystemSetting::create(['key'=>'sms_api_url','value'=>'https://api.textit.biz','type'=>'string']);SystemSetting::create(['key'=>'sms_api_version','value'=>'v1','type'=>'string']);SystemSetting::create(['key'=>'sms_api_key_encrypted','value'=>Crypt::encryptString('secret-key'),'type'=>'encrypted']);Http::fake(['api.textit.biz'=>Http::response(['message_id'=>'MSG-1'],200)]);$result=app(TextItSmsService::class)->send('0771234567','Test message');$this->assertTrue($result['success']);$this->assertSame('94771234567',$result['recipient']);Http::assertSent(fn($request)=>$request->url()==='https://api.textit.biz'&&$request->hasHeader('X-API-VERSION','v1')&&$request->hasHeader('Authorization','Basic secret-key')&&$request['to']==='94771234567'&&$request['text']==='Test message');}
 public function test_textit_invalid_api_key_is_reported_without_throwing(){SystemSetting::create(['key'=>'sms_enabled','value'=>'true','type'=>'boolean']);SystemSetting::create(['key'=>'sms_api_url','value'=>'https://api.textit.biz','type'=>'string']);SystemSetting::create(['key'=>'sms_api_key_encrypted','value'=>Crypt::encryptString('bad-key'),'type'=>'encrypted']);Http::fake(['api.textit.biz'=>Http::response(['error'=>'unauthorized'],401)]);$result=app(TextItSmsService::class)->send('+94771234567','Test');$this->assertFalse($result['success']);$this->assertStringContainsString('rejected the API key',$result['failure_reason']);}
 public function test_textit_timeout_is_returned_as_financially_safe_failure(){SystemSetting::create(['key'=>'sms_enabled','value'=>'true','type'=>'boolean']);SystemSetting::create(['key'=>'sms_api_url','value'=>'https://api.textit.biz','type'=>'string']);SystemSetting::create(['key'=>'sms_retry_count','value'=>'0','type'=>'integer']);SystemSetting::create(['key'=>'sms_api_key_encrypted','value'=>Crypt::encryptString('key'),'type'=>'encrypted']);Http::fake(fn()=>throw new ConnectionException('timeout'));$result=app(TextItSmsService::class)->send('94771234567','Test');$this->assertFalse($result['success']);$this->assertSame('network_failure',$result['status']);}
}
