@php($editing=isset($shop))
<x-layouts.app :title="$editing?'Edit Shop':'Add Shop'"><div class="mx-auto max-w-5xl"><div class="mb-7"><p class="eyebrow">Shop Management</p><h1 class="page-title">{{ $editing?'Edit Shop':'Add Shop Owner' }}</h1><p class="page-copy">Existing device commission snapshots never change when this profile is edited.</p></div>
<form class="panel p-6 space-y-6" method="post" action="{{ $editing?route('shops.update',$shop):route('shops.store') }}">@csrf @if($editing)@method('put')@endif<div class="form-grid">
@foreach([['name','Shop name'],['owner_name','Owner name'],['username','Login username'],['email','Login email'],['mobile','Mobile number'],['address','Address']] as [$name,$label])<label class="field-label">{{ $label }} <x-required/><input class="field-input" name="{{ $name }}" value="{{ old($name,$shop->$name??'') }}" required></label>@endforeach
<label class="field-label">Alternative mobile<input class="field-input" name="alternative_mobile" value="{{ old('alternative_mobile',$shop->alternative_mobile??'') }}"></label><label class="field-label">City<input class="field-input" name="city" value="{{ old('city',$shop->city??'') }}"></label><label class="field-label">District<input class="field-input" name="district" value="{{ old('district',$shop->district??'') }}"></label>
<label class="field-label">Business registration number<input class="field-input" name="business_registration_number" value="{{ old('business_registration_number',$shop->business_registration_number??'') }}"></label><label class="field-label">Shop reference code<x-info text="Unique platform reference used in reports and settlement records."/><input class="field-input" name="reference_code" value="{{ old('reference_code',$shop->reference_code??'') }}"></label>
<label class="field-label">Commission percentage <x-required/><x-info text="The percentage of this shop’s registered phone selling price payable to the DeviceGuard platform."/><input class="field-input" type="number" step=".0001" min="0" max="100" name="commission_percentage" value="{{ old('commission_percentage',$shop->commission_percentage??5) }}" required></label>
<label class="field-label">Commission calculation basis <x-required/><select class="field-input" name="commission_basis">@foreach(['selling_price_percentage'=>'Percentage of total selling price','financed_balance_percentage'=>'Percentage of financed balance','fixed_per_device'=>'Fixed amount per device','custom_per_device'=>'Custom per-device commission'] as $v=>$label)<option value="{{ $v }}" @selected(old('commission_basis',$shop->commission_basis??'selling_price_percentage')===$v)>{{ $label }}</option>@endforeach</select></label>
<label class="field-label">Fixed commission amount<input class="field-input" type="number" step=".01" name="fixed_commission_amount" value="{{ old('fixed_commission_amount',$shop->fixed_commission_amount??0) }}"></label><label class="field-label">Account status <x-required/><select class="field-input" name="status"><option value="active">Active</option><option value="inactive">Inactive</option></select></label>
<label class="field-label">{{ $editing?'New temporary password (optional)':'Temporary password' }} @unless($editing)<x-required/>@endunless<input class="field-input" type="password" name="temporary_password" @required(!$editing)></label>
</div><div class="grid gap-3 sm:grid-cols-2">@foreach(['sms_enabled'=>'SMS notifications','device_registration_enabled'=>'Device registration','lock_unlock_enabled'=>'Lock/unlock permission','staff_accounts_enabled'=>'Staff accounts'] as $name=>$label)<label class="flex gap-2 rounded-xl bg-slate-50 p-3"><input type="checkbox" name="{{ $name }}" value="1" @checked(old($name,$shop->$name??true))> {{ $label }} enabled</label>@endforeach</div><label class="field-label">Notes<textarea class="field-input" name="notes">{{ old('notes',$shop->notes??'') }}</textarea></label><button class="primary-button">{{ $editing?'Save changes':'Create Shop Owner login' }}</button></form></div></x-layouts.app>
