<x-layouts.app :title="$shop->name">
    <div class="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p class="eyebrow">{{ $shop->reference_code }}</p><h1 class="page-title">{{ $shop->name }}</h1><p class="page-copy">{{ $shop->owner_name }} · {{ $shop->mobile }}</p></div><a class="secondary-button" href="{{ route('shops.edit',$shop) }}">Edit Shop</a></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Customers',$shop->customers_count],['Devices',$shop->devices_count],['Commission',number_format($shop->commissions->sum('commission_amount'),2).' LKR'],['Outstanding',number_format($shop->commissions->sum('outstanding_amount'),2).' LKR']] as [$label,$value])<article class="metric-card"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-3 text-2xl font-black">{{ $value }}</p></article>@endforeach</div>
    <div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="panel p-6"><h2 class="section-title">Shop policy</h2><dl class="details-grid mt-4"><div><dt>Commission</dt><dd>{{ $shop->commission_percentage }}%</dd></div><div><dt>Basis</dt><dd>{{ str_replace('_',' ',$shop->commission_basis) }}</dd></div><div><dt>Status</dt><dd>{{ $shop->status }}</dd></div><div><dt>Separate logins</dt><dd>{{ $shop->users->count() }}</dd></div></dl></section><section class="panel p-6"><h2 class="section-title">Shop users</h2>@foreach($shop->users as $user)<div class="mt-3 rounded-xl bg-slate-50 p-3"><strong>{{ $user->name }}</strong> · {{ str_replace('_',' ',$user->role) }}<br><small>{{ $user->email }}</small></div>@endforeach</section></div>
    <section class="panel mt-6"><div class="panel-header"><h2 class="section-title">Managed devices</h2></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Device</th><th>Customer</th><th>Status</th><th>Commission</th></tr></thead><tbody>@foreach($shop->devices as $device)<tr><td><a class="font-bold text-indigo-600" href="{{ route('devices.show',$device) }}">{{ $device->brand }} {{ $device->model }}</a></td><td>{{ $device->customer->name }}</td><td>{{ $device->status }}</td><td>LKR {{ number_format($device->commission?->commission_amount??0,2) }}</td></tr>@endforeach</tbody></table></div></section>

    <section class="panel mt-6 p-6"><h2 class="section-title">Account actions</h2><div class="mt-5 grid gap-5 xl:grid-cols-3">
        <form class="space-y-3" method="post" action="{{ route('shops.status',$shop) }}">@csrf<input type="hidden" name="status" value="{{ $shop->status==='active'?'inactive':'active' }}"><h3 class="font-bold">{{ $shop->status==='active'?'Deactivate':'Activate' }} Shop Owner</h3><input class="field-input" type="password" name="password" placeholder="Super Admin password" required><textarea class="field-input" name="reason" placeholder="Reason" required></textarea><button class="{{ $shop->status==='active'?'danger-button':'primary-button' }}">{{ $shop->status==='active'?'Deactivate':'Activate' }}</button></form>
        <form class="space-y-3" method="post" action="{{ route('shops.reset-password',$shop) }}">@csrf<h3 class="font-bold">Reset Shop Owner password</h3><input class="field-input" type="password" name="temporary_password" placeholder="New temporary password" minlength="10" required><input class="field-input" type="password" name="temporary_password_confirmation" placeholder="Confirm temporary password" required><input class="field-input" type="password" name="password" placeholder="Super Admin password" required><textarea class="field-input" name="reason" placeholder="Reason" required></textarea><button class="secondary-button">Reset password</button></form>
        <form class="space-y-3" method="post" action="{{ route('shops.archive',$shop) }}">@csrf<h3 class="font-bold">Archive Shop Owner</h3><p class="text-sm text-slate-500">Financial and device history is preserved. Managed devices are not released.</p><input class="field-input" type="password" name="password" placeholder="Super Admin password" required><textarea class="field-input" name="reason" placeholder="Reason" required></textarea><button class="danger-button">Archive shop</button></form>
    </div></section>

    <details class="panel mt-6 p-5"><summary class="cursor-pointer font-bold text-amber-800">Recalculate existing device commission</summary><p class="mt-3 text-sm">Affected devices: {{ $shop->commissions->count() }}. Old total: LKR {{ number_format($shop->commissions->sum('commission_amount'),2) }}. This explicit action records an adjustment per device.</p><form class="mt-4 space-y-3" method="post" action="{{ route('shops.recalculate-commission',$shop) }}">@csrf<input class="field-input" type="password" name="password" placeholder="Super Admin password" required><textarea class="field-input" name="reason" placeholder="Reason" required></textarea><label class="flex gap-2"><input type="checkbox" name="confirmed" value="1" required> Confirm recalculation of {{ $shop->commissions->count() }} devices</label><button class="danger-button">Recalculate historical commissions</button></form></details>
</x-layouts.app>
