<x-layouts.app title="Device Setup Wizard"><div class="mx-auto max-w-5xl"><div class="mb-7"><p class="eyebrow">Guided Device Setup</p><h1 class="page-title">{{ $setup->device->brand }} {{ $setup->device->model }}</h1><p class="page-copy">{{ ucfirst($setup->computer_os) }} · {{ ucfirst($setup->brand_group) }} · Resume at step {{ $setup->current_step }}</p></div>
@php
    $pct = round(($setup->current_step - 1) / max(1, count($steps)) * 100);
    $step = $steps[$setup->current_step - 1] ?? $steps[count($steps) - 1];
@endphp
<div class="mb-6 h-3 overflow-hidden rounded-full bg-slate-200"><div class="h-full bg-indigo-600" style="width:{{ $pct }}%"></div></div>
<section class="panel p-7"><p class="eyebrow">Step {{ $setup->current_step }} of {{ count($steps) }}</p><h2 class="text-2xl font-black">{{ $step['title'] }}</h2>@if($step['command'])<div class="mt-5 flex gap-2"><code id="setup-command" class="flex-1 rounded-xl bg-slate-950 p-4 text-sm text-white">{{ $step['command'] }}</code><button class="secondary-button" onclick="navigator.clipboard.writeText(document.getElementById('setup-command').textContent)">Copy command</button></div>@endif
<div class="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm"><strong>Required warning:</strong> The browser cannot run ADB or inspect your computer. Perform each command locally and continue only on a phone the shop is authorized to manage. Never remove accounts automatically or bypass Android security.</div>
<form class="mt-6 space-y-4" method="post" action="{{ route('setup.step',$setup) }}">@csrf<input type="hidden" name="step" value="{{ $setup->current_step }}"><input type="hidden" name="direction" value="next"><label class="flex gap-2"><input type="checkbox" name="completed" value="1" required> I completed and verified this step.</label><textarea class="field-input" name="notes" placeholder="Optional setup notes"></textarea><div class="flex justify-end"><button class="primary-button">{{ $setup->current_step===count($steps)?'Complete setup':'Next step' }} →</button></div></form>@if($setup->current_step>1)<form class="mt-3" method="post" action="{{ route('setup.step',$setup) }}">@csrf<input type="hidden" name="step" value="{{ $setup->current_step }}"><input type="hidden" name="direction" value="previous"><button class="secondary-button">← Previous step</button></form>@endif</section>
<div class="mt-6 flex flex-wrap gap-3"><a class="secondary-button" href="{{ $helperUrl }}">Download authenticated {{ $setup->computer_os==='macos'?'macOS shell':'Windows PowerShell' }} helper</a><details><summary class="secondary-button cursor-pointer">Troubleshooting</summary><div class="mt-2 max-w-2xl space-y-3 rounded-xl border bg-white p-4 text-sm">@foreach(['adb command not found'=>'Install only the official Android Platform Tools, then open a new terminal and run adb version.','Device unauthorized or offline'=>'Unlock the phone, accept the USB-debugging fingerprint, revoke USB authorizations if needed, reconnect, then run adb devices.','No device detected'=>'Use a data-capable cable, change USB port/mode, and install the official manufacturer driver on Windows.','INSTALL_FAILED_USER_RESTRICTED'=>'Approve installation on the phone and review the selected brand USB-installation setting; do not bypass manufacturer security.','APK signature mismatch'=>'Stop. Verify the configured HTTPS APK and SHA-256 checksum before retrying.','Accounts already exist'=>'Remove accounts manually in Android Settings or factory-reset with customer authorization before Device Owner setup.','Unknown admin or Device Owner blocked'=>'Confirm the package path, factory-reset state, and absence of accounts/owners; never root or bypass Android security.','FCM token missing or dispatched but not received'=>'Check network, Google Play Services, notification/background permissions, battery restrictions, and the server Firebase configuration.','Worker queued but not started'=>'Check the Laravel queue worker and scheduler; sync delivery remains the shared-hosting fallback.','Automatic lock or unlock failed'=>'Verify Device Owner, capabilities, latest signed policy, heartbeat, battery/background settings, and the last confirmed command result.'] as $error=>$solution)<div><strong>{{ $error }}</strong><p class="text-slate-600">{{ $solution }}</p></div>@endforeach</div></details></div></div></x-layouts.app>
