<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
class BusinessReportController extends Controller{
 public function __invoke(Request $r,string $type){abort_unless($r->user()->isSuperAdmin()||$r->user()->canShop('reports.view'),403);abort_unless(in_array($type,['shops','customers','devices','installments','payments','outstanding','overdue','commissions','settlements','sms','setup'],true),404);[$headers,$rows]=$this->data($r,$type);if($r->format==='csv')return response()->streamDownload(function()use($headers,$rows){$o=fopen('php://output','w');fputcsv($o,$headers);$rows->chunk(500)->each(fn($chunk)=>$chunk->each(fn($row)=>fputcsv($o,$row)));fclose($o);},"$type-report.csv",['Content-Type'=>'text/csv']);return view('reports.business',compact('type','headers','rows'));}
 private function scope($q,Request $r){return $q->when(!$r->user()->isSuperAdmin(),fn($x)=>$x->where('shop_id',$r->user()->shop_id))->when($r->date_from,fn($x,$v)=>$x->whereDate('created_at','>=',$v))->when($r->date_to,fn($x,$v)=>$x->whereDate('created_at','<=',$v));}
 private function data(Request $r,string $type):array{return match($type){
 'shops'=>[['Shop','Owner','Status','Commission %','Devices'],\App\Models\Shop::withCount('devices')->when(!$r->user()->isSuperAdmin(),fn($q)=>$q->whereKey($r->user()->shop_id))->get()->map(fn($x)=>[$x->name,$x->owner_name,$x->status,$x->commission_percentage,$x->devices_count])],
 'customers'=>[['Customer','Phone','NIC','Devices'],$this->scope(\App\Models\Customer::withCount('devices'),$r)->get()->map(fn($x)=>[$x->name,$x->phone,$x->nic,$x->devices_count])],
 'devices'=>[['Device','Customer','Shop','Selling price','Status'],$this->scope(\App\Models\Device::with(['customer','shop']),$r)->get()->map(fn($x)=>[$x->brand.' '.$x->model,$x->customer->name,$x->shop?->name,$x->selling_price,$x->status])],
 'installments','overdue'=>[['Device','Due date','Expected','Paid','Remaining','Status'],$this->scope(\App\Models\InstallmentSchedule::with('financing.device'),$r)->when($type==='overdue',fn($q)=>$q->where('status','overdue'))->get()->map(fn($x)=>[$x->financing->device->brand.' '.$x->financing->device->model,$x->due_date,$x->expected_amount,$x->amount_paid,$x->remaining_amount,$x->status])],
 'payments'=>[['Receipt','Customer','Device','Date','Method','Amount','Status'],$this->scope(\App\Models\CustomerPayment::with(['customer','device']),$r)->get()->map(fn($x)=>[$x->receipt_number,$x->customer->name,$x->device->brand.' '.$x->device->model,$x->payment_date,$x->payment_method,$x->amount,$x->status])],
 'outstanding'=>[['Device','Financed','Paid','Remaining','Status'],$this->scope(\App\Models\DeviceFinancing::with('device'),$r)->where('remaining_balance','>',0)->get()->map(fn($x)=>[$x->device->brand.' '.$x->device->model,$x->financed_balance,$x->total_paid,$x->remaining_balance,$x->status])],
 'commissions'=>[['Shop','Device','Rate','Basis','Commission','Paid','Outstanding'],$this->scope(\App\Models\DeviceCommission::with(['shop','device']),$r)->get()->map(fn($x)=>[$x->shop->name,$x->device->brand.' '.$x->device->model,$x->captured_percentage,$x->calculation_basis,$x->commission_amount,$x->paid_amount,$x->outstanding_amount])],
 'settlements'=>[['Number','Shop','Date','Amount','Method','Status'],$this->scope(\App\Models\PlatformSettlement::with('shop'),$r)->get()->map(fn($x)=>[$x->settlement_number,$x->shop->name,$x->payment_date,$x->amount,$x->payment_method,$x->status])],
 'sms'=>[['Shop','Recipient','Template','Sent','Delivery','Failure'],$this->scope(\App\Models\SmsLog::with('shop'),$r)->get()->map(fn($x)=>[$x->shop?->name,$x->recipient_number,$x->template,$x->sent_status,$x->delivery_status,$x->failure_reason])],
 'setup'=>[['Device','OS','Brand group','Step','Status','Completed'],$this->scope(\App\Models\DeviceSetupSession::with('device'),$r)->get()->map(fn($x)=>[$x->device->brand.' '.$x->device->model,$x->computer_os,$x->brand_group,$x->current_step,$x->status,$x->completed_at])],
 };}
}
