<?php
namespace App\Http\Controllers;
use App\Models\CustomerPayment;use App\Models\Device;use App\Services\CustomerPaymentService;use App\Services\AuditService;use Illuminate\Http\Request;
class CustomerPaymentController extends Controller{
 public function index(Request $r){$payments=CustomerPayment::with(['customer','device'])->when(!$r->user()->isSuperAdmin(),fn($q)=>$q->where('shop_id',$r->user()->shop_id))->latest('payment_date')->paginate(30);return view('payments.index',compact('payments'));}
 public function create(Request $r){abort_unless($r->user()->canShop('payments.create'),403);return view('payments.create',['devices'=>Device::visibleTo($r->user())->with(['customer','financing'])->whereHas('financing')->get()]);}
 public function store(Request $r,CustomerPaymentService $service,AuditService $audit){abort_unless($r->user()->canShop('payments.create'),403);$d=$r->validate(['device_id'=>['required','integer'],'amount'=>['required','numeric','min:0.01'],'payment_date'=>['required','date'],'payment_method'=>['required','in:cash,bank_transfer,card,qr_payment,cheque,other'],'reference_number'=>['nullable'],'notes'=>['nullable'],'send_sms'=>['nullable','boolean'],'idempotency_key'=>['required','uuid']]);$p=$service->receive($d,$r->user());$audit->record('PAYMENT_RECEIVED','Customer payment received',$r->user(),$p->device,[],['receipt_number'=>$p->receipt_number,'amount'=>$p->amount]);return redirect()->route('payments.show',$p)->with('success','Payment received. SMS status is shown on the receipt.');}
 public function show(Request $r,CustomerPayment $payment){abort_unless($r->user()->isSuperAdmin()||$payment->shop_id===$r->user()->shop_id,403);return view('payments.show',['payment'=>$payment->load(['customer','device.financing.installments','allocations.installment','reversal'])]);}
 public function reverse(Request $r,CustomerPayment $payment,CustomerPaymentService $service,AuditService $audit){abort_unless($r->user()->isSuperAdmin()||($payment->shop_id===$r->user()->shop_id&&$r->user()->canShop('payments.reverse')),403);$d=$r->validate(['password'=>['required','current_password'],'reason'=>['required'],'confirmed'=>['accepted']]);$service->reverse($payment->load(['allocations.installment','device.financing']),$r->user(),$d['reason']);$audit->record('PAYMENT_REVERSED','Payment reversed: '.$d['reason'],$r->user(),$payment->device);return back()->with('success','Payment reversed through an immutable reversal entry.');}
}
