<?php
namespace App\Http\Controllers;
use App\Models\Device;use App\Models\DeviceProvisioningToken;use App\Services\AuditService;use App\Services\QrProvisioningService;use Illuminate\Http\Request;
class DeviceProvisioningController extends Controller {
 public function generate(Request $r,Device $device,QrProvisioningService $qr,AuditService $audit){$this->authorize('managePin',$device);$r->validate(['password'=>['required','current_password']]);abort_if($device->isReleased(),422,'Released devices cannot be provisioned.');abort_unless($device->management_pin_hash,422,'Configure the Management PIN first.');abort_unless($qr->configured(),422,'QR provisioning settings are incomplete or disabled.');[$token,$payload]=$qr->generate($device,$r->user()->id);$audit->record('QR_GENERATED','Full Management QR generated',$r->user(),$device);session(['provisioning_payload_'.$token->id=>$payload]);return redirect()->route('devices.provisioning.show',[$device,$token]);}
 public function show(Request $r,Device $device,DeviceProvisioningToken $token,QrProvisioningService $qr,AuditService $audit){$this->authorize('managePin',$device);abort_unless($token->device_id===$device->id,404);$payload=session('provisioning_payload_'.$token->id);abort_unless($payload,410,'The QR secret is no longer available. Regenerate the QR.');$audit->record('QR_VIEWED','Full Management QR viewed',$r->user(),$device);return view('devices.provisioning',compact('device','token','payload'));}
 public function image(Request $r,Device $device,DeviceProvisioningToken $token,QrProvisioningService $qr){$this->authorize('managePin',$device);$payload=session('provisioning_payload_'.$token->id);abort_unless($payload,410);return response($qr->png($payload),200,['Content-Type'=>'image/png','Content-Disposition'=>$r->boolean('download')?'attachment; filename="deviceguard-provisioning.png"':'inline']);}
 public function revoke(Request $r,Device $device,DeviceProvisioningToken $token,AuditService $audit){$this->authorize('managePin',$device);$token->update(['status'=>'revoked','revoked_at'=>now()]);$audit->record('QR_REVOKED','Full Management QR revoked',$r->user(),$device);return redirect()->route('devices.show',$device)->with('success','Provisioning QR revoked.');}
}
