<x-layouts.app title="QR Provisioning Settings"><div class="mx-auto max-w-4xl"><p class="eyebrow">Super Admin</p><h1 class="page-title">QR Provisioning Settings</h1><p class="page-copy">Configure the public HTTPS services used by Android Setup Wizard.</p>
<form method="post" action="{{ route('settings.qr-provisioning.update') }}" class="panel mt-6 space-y-4 p-6">@csrf @method('put')
@foreach(['provisioning_api_url'=>'Production Laravel API URL','provisioning_apk_url'=>'DeviceGuard APK HTTPS download URL','provisioning_apk_version'=>'DeviceGuard APK version','provisioning_apk_checksum'=>'Signing-certificate checksum','provisioning_qr_expiry_minutes'=>'QR expiry time in minutes'] as $key=>$label)<label class="field-label">{{ $label }}<input class="field-input" name="{{ $key }}" value="{{ old($key,App\Models\SystemSetting::value($key,$key==='provisioning_qr_expiry_minutes'?30:'')) }}" @if(in_array($key,['provisioning_api_url','provisioning_apk_url'])) type="url" @endif required></label>@endforeach
<label class="field-label">Default support phone<input class="field-input" name="provisioning_support_phone" value="{{ old('provisioning_support_phone',App\Models\SystemSetting::value('provisioning_support_phone','')) }}"></label>
<section class="rounded-2xl border border-slate-200 p-4"><h2 class="font-bold">Optional branch Wi-Fi</h2><div class="form-grid mt-4">
<label class="field-label">Wi-Fi SSID<input class="field-input" type="text" name="wifi_ssid" maxlength="32" value="{{ old('wifi_ssid',App\Models\SystemSetting::value('provisioning_wifi_ssid','')) }}"><span class="mt-1 text-xs font-normal text-slate-500">Optional. Leave blank to select Wi-Fi manually during phone setup.</span></label>
<label class="field-label">Wi-Fi security type<select class="field-input" name="wifi_security_type"><option value="WPA" @selected(old('wifi_security_type',App\Models\SystemSetting::value('provisioning_wifi_security_type','WPA'))==='WPA')>WPA/WPA2</option><option value="WEP" @selected(old('wifi_security_type',App\Models\SystemSetting::value('provisioning_wifi_security_type'))==='WEP')>WEP</option><option value="NONE" @selected(old('wifi_security_type',App\Models\SystemSetting::value('provisioning_wifi_security_type'))==='NONE')>Open network</option></select></label>
<label class="field-label">Wi-Fi password<input class="field-input" type="password" name="wifi_password" value="" autocomplete="new-password"><span class="mt-1 text-xs font-normal text-slate-500">Required only when an SSID is entered and the Wi-Fi network is password protected. Leave blank to keep the saved password when the SSID is unchanged.</span></label>
<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="wifi_hidden" value="1" @checked(old('wifi_hidden',App\Models\SystemSetting::value('provisioning_wifi_hidden',false)))> Hidden Wi-Fi network</label>
</div></section>
<label class="flex gap-3"><input type="checkbox" name="qr_provisioning_enabled" value="1" @checked(App\Models\SystemSetting::value('qr_provisioning_enabled',false))> QR provisioning enabled</label><button class="primary-button">Save settings</button></form>
@if(session('configuration_validation'))
@php($validation=session('configuration_validation'))
<section class="mt-6 rounded-2xl border p-5 {{ $validation['passed'] ? 'border-emerald-200 bg-emerald-50' : 'border-red-200 bg-red-50' }}">
<div class="flex items-center justify-between gap-3"><h2 class="font-black {{ $validation['passed'] ? 'text-emerald-900' : 'text-red-900' }}">Configuration validation {{ $validation['passed'] ? 'passed' : 'needs attention' }}</h2><span class="status-pill {{ $validation['passed'] ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800' }}">{{ $validation['passed'] ? 'Valid' : 'Failed' }}</span></div>
<div class="mt-4 grid gap-2">@foreach($validation['checks'] as $label=>$check)<div class="flex items-start justify-between gap-4 rounded-xl bg-white/80 px-4 py-3 text-sm"><div><strong>{{ $label }}</strong><p class="mt-1 text-xs text-slate-600">{{ $check['message'] }}</p></div><strong class="{{ $check['passed'] ? 'text-emerald-700' : 'text-red-700' }}">{{ $check['passed'] ? 'Passed' : 'Failed' }}</strong></div>@endforeach</div>
@if($validation['errors'])<ul class="mt-4 list-disc space-y-1 pl-5 text-sm text-red-800">@foreach($validation['errors'] as $error)<li>{{ $error }}</li>@endforeach</ul>@endif
</section>
@endif
<div class="mt-4 flex gap-3"><form method="POST" action="{{ route('settings.qr-provisioning.validate') }}">@csrf<button type="submit" class="secondary-button">Validate Configuration</button></form>@if(App\Models\SystemSetting::value('provisioning_apk_url'))<a class="secondary-button" href="{{ App\Models\SystemSetting::value('provisioning_apk_url') }}" target="_blank" rel="noopener noreferrer">Test APK Download</a>@endif</div></div></x-layouts.app>
