<x-layouts.app title="SMS Logs">
    <div class="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p class="eyebrow">Communication</p><h1 class="page-title">SMS Logs</h1><p class="page-copy">Delivery attempts, failures, retries, and provider references.</p></div>@if(auth()->user()->isSuperAdmin())<a class="secondary-button" href="{{ route('settings.sms') }}">SMS Gateway & Templates</a>@endif</div>
    <section class="panel">
        <form class="panel-header flex-wrap" method="get"><input class="field-input max-w-xs" name="search" value="{{ request('search') }}" placeholder="Recipient or SMS type"><select class="field-input max-w-48" name="status"><option value="">All statuses</option>@foreach(['pending','sent','delivered','failed','retrying','skipped'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="secondary-button">Filter</button><a class="secondary-button" href="{{ route('reports.business',['type'=>'sms','format'=>'csv']) }}">Export CSV</a></form>
        <div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Date</th><th>Shop</th><th>Recipient</th><th>Type</th><th>Provider</th><th>Message ID</th><th>Status</th><th>Failure</th><th></th></tr></thead><tbody>
        @forelse($logs as $log)<tr><td>{{ $log->created_at->format('d M Y H:i') }}</td><td>{{ $log->shop?->name??'Platform' }}</td><td>{{ substr($log->recipient_number,0,4).'••••'.substr($log->recipient_number,-3) }}</td><td>{{ str_replace('_',' ',$log->template) }}</td><td>{{ $log->provider?:'—' }}</td><td>{{ $log->provider_message_id?:'—' }}</td><td><span class="status-pill {{ in_array($log->sent_status,['sent','delivered'])?'bg-emerald-50 text-emerald-700':($log->sent_status==='failed'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-700') }}">{{ $log->sent_status }}</span></td><td>{{ $log->failure_reason?:'—' }}</td><td>@if($log->sent_status==='failed')<form method="post" action="{{ route('sms.retry',$log) }}">@csrf<button class="text-indigo-600 font-bold">Retry</button></form>@endif</td></tr>@empty<tr><td colspan="9" class="py-10 text-center">No SMS activity found.</td></tr>@endforelse
        </tbody></table></div><div class="p-5">{{ $logs->links() }}</div>
    </section>
</x-layouts.app>
