<x-layouts.app :title="ucfirst(str_replace('-',' ',$section)).' Settings'">
    <div class="mb-7"><p class="eyebrow">Super Admin Settings</p><h1 class="page-title">{{ ucfirst(str_replace('-',' ',$section)) }}</h1><p class="page-copy">Sensitive changes require your current Super Admin password and are written to the audit log.</p></div>

    @if($section==='roles')
        <section class="panel overflow-x-auto"><div class="panel-header"><div><h2 class="section-title">Users, roles and tenant assignment</h2><p class="section-copy">Shop staff permissions are managed by their Shop Owner. Platform roles are displayed here for oversight.</p></div></div><table class="data-table"><thead><tr><th>User</th><th>Email</th><th>Platform role</th><th>Staff role</th><th>Shop</th><th>Permissions</th><th>Status</th></tr></thead><tbody>@foreach($users as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td>{{ str_replace('_',' ',$user->role) }}</td><td>{{ str_replace('_',' ',$user->staff_role??'—') }}</td><td>{{ $user->shop?->name??'Platform' }}</td><td>{{ implode(', ',$user->shop_permissions??[])?:'Role defaults' }}</td><td><span class="status-pill {{ $user->is_active?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700' }}">{{ $user->is_active?'active':'inactive' }}</span></td></tr>@endforeach</tbody></table><div class="p-5">{{ $users->links() }}</div></section>
    @else
        <form class="panel space-y-5 p-6" method="post" action="{{ route('settings.system.update',$section) }}">@csrf @method('put')
            @if($section==='general')
                <div class="form-grid"><label class="field-label">Platform name <x-required/><input class="field-input" name="platform_name" value="{{ old('platform_name',App\Models\SystemSetting::value('platform_name','DeviceGuard')) }}" required></label><label class="field-label">Timezone <x-required/><input class="field-input" name="timezone" value="{{ old('timezone',App\Models\SystemSetting::value('timezone',config('app.timezone'))) }}" required></label><label class="field-label">Currency <x-required/><input class="field-input uppercase" name="currency" maxlength="3" value="{{ old('currency',App\Models\SystemSetting::value('currency','LKR')) }}" required></label><label class="field-label">Support phone<input class="field-input" name="support_phone" value="{{ old('support_phone',App\Models\SystemSetting::value('support_phone')) }}"></label><label class="field-label">Support email<input class="field-input" type="email" name="support_email" value="{{ old('support_email',App\Models\SystemSetting::value('support_email')) }}"></label></div>
            @elseif($section==='commission')
                <div class="form-grid"><label class="field-label">Default commission percentage <x-required/><x-info text="Default percentage proposed when creating a new Shop Owner."/><input class="field-input" type="number" step=".0001" name="default_commission_percentage" value="{{ old('default_commission_percentage',App\Models\SystemSetting::value('default_commission_percentage',5)) }}" required></label><label class="field-label">Minimum percentage <x-required/><input class="field-input" type="number" step=".0001" name="minimum_commission_percentage" value="{{ old('minimum_commission_percentage',App\Models\SystemSetting::value('minimum_commission_percentage',0)) }}" required></label><label class="field-label">Maximum percentage <x-required/><input class="field-input" type="number" step=".0001" name="maximum_commission_percentage" value="{{ old('maximum_commission_percentage',App\Models\SystemSetting::value('maximum_commission_percentage',100)) }}" required></label><label class="field-label">Calculation basis<select class="field-input" name="default_commission_basis">@foreach(['selling_price_percentage','financed_balance_percentage','fixed_per_device','custom_per_device'] as $basis)<option value="{{ $basis }}" @selected(App\Models\SystemSetting::value('default_commission_basis','selling_price_percentage')===$basis)>{{ ucwords(str_replace('_',' ',$basis)) }}</option>@endforeach</select></label><label class="field-label">Settlement allocation<select class="field-input" name="default_settlement_allocation">@foreach(['oldest_first','manual','unallocated_credit'] as $method)<option value="{{ $method }}" @selected(App\Models\SystemSetting::value('default_settlement_allocation','oldest_first')===$method)>{{ ucwords(str_replace('_',' ',$method)) }}</option>@endforeach</select></label><label class="flex items-center gap-2"><input type="checkbox" name="allow_custom_shop_percentage" value="1" @checked(App\Models\SystemSetting::value('allow_custom_shop_percentage',true))> Allow custom shop percentage</label></div>
            @elseif($section==='device')
                <div class="form-grid"><label class="field-label">Management PIN length <x-required/><input class="field-input" type="number" min="4" max="8" name="management_pin_length" value="{{ old('management_pin_length',App\Models\SystemSetting::value('management_pin_length',4)) }}" required></label><label class="field-label">Command expiry in minutes <x-required/><input class="field-input" type="number" min="1" max="1440" name="device_command_expiry_minutes" value="{{ old('device_command_expiry_minutes',App\Models\SystemSetting::value('device_command_expiry_minutes',15)) }}" required></label><label class="field-label">Activation Code Validity (minutes) <x-required/><input class="field-input" type="number" min="60" max="10080" step="60" list="activation-validity-presets" name="device_activation_code_expiry_minutes" value="{{ old('device_activation_code_expiry_minutes',App\Models\SystemSetting::value('device_activation_code_expiry_minutes',1440)) }}" required><datalist id="activation-validity-presets"><option value="60">1 hour</option><option value="360">6 hours</option><option value="720">12 hours</option><option value="1440">24 hours</option><option value="2880">48 hours</option></datalist><span class="mt-1 text-xs font-normal text-slate-500">Choose a preset or enter custom whole hours. New codes use server time; existing codes keep their original expiry.</span></label><label class="flex items-center gap-2"><input type="checkbox" name="send_activation_code_by_sms" value="1" @checked(App\Models\SystemSetting::value('send_activation_code_by_sms',false))> Send activation code by SMS (default off)</label><label class="flex items-center gap-2"><input type="checkbox" name="default_lock_enabled" value="1" @checked(App\Models\SystemSetting::value('default_lock_enabled',true))> Lock commands enabled by default</label><label class="flex items-center gap-2"><input type="checkbox" name="default_unlock_enabled" value="1" @checked(App\Models\SystemSetting::value('default_unlock_enabled',true))> Unlock commands enabled by default</label></div><a class="secondary-button" href="{{ route('settings.offline-protection') }}">Configure offline protection defaults</a>
            @else
                <label class="field-label">macOS setup instructions <x-required/><textarea class="field-input min-h-52" name="macos_setup_instructions" required>{{ old('macos_setup_instructions',App\Models\SystemSetting::value('macos_setup_instructions','Use the guided macOS workflow and authenticated helper.')) }}</textarea></label><label class="field-label">Windows setup instructions <x-required/><textarea class="field-input min-h-52" name="windows_setup_instructions" required>{{ old('windows_setup_instructions',App\Models\SystemSetting::value('windows_setup_instructions','Use the guided Windows workflow and authenticated helper.')) }}</textarea></label><label class="field-label">Troubleshooting guidance<textarea class="field-input min-h-40" name="setup_troubleshooting">{{ old('setup_troubleshooting',App\Models\SystemSetting::value('setup_troubleshooting')) }}</textarea></label>
            @endif
            <label class="field-label">Super Admin password <x-required/><input class="field-input" type="password" name="password" autocomplete="current-password" required></label><button class="primary-button">Save settings</button>
        </form>
    @endif
</x-layouts.app>
